import { z } from 'zod'

export const QuotationLineSchema = z.object({
  item_id: z.string().uuid().optional(),
  item_code: z.string().max(50).optional(),
  item_name: z.string().max(200).optional(),
  description: z.string().max(1000).optional(),
  qty: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
  unit: z.string().default('piece'),
  unit_price: z.number().min(0, 'السعر يجب أن يكون أكبر من أو يساوي صفر'),
  discount_percent: z.number().min(0).max(100).optional(),
  tax_rate: z.number().min(0).optional(),
  warehouse_id: z.string().uuid().optional(),
  delivery_date: z.string().optional(),
})

export const CreateQuotationSchema = z.object({
  customer_id: z.string().uuid('العميل مطلوب'),
  customer_name: z.string().max(200).optional(),
  customer_tax_no: z.string().max(50).optional(),
  branch_id: z.string().uuid().optional(),
  cost_center_id: z.string().uuid().optional(),
  currency: z.string().default('SAR'),
  valid_until: z.string().optional(),
  notes: z.string().max(2000).optional(),
  terms: z.string().max(2000).optional(),
  created_by: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
  lines: z.array(QuotationLineSchema).min(1, 'يجب إضافة بند واحد على الأقل'),
})

export const CreateOrderSchema = z.object({
  quotation_id: z.string().uuid().optional(),
  customer_id: z.string().uuid('العميل مطلوب'),
  customer_name: z.string().max(200).optional(),
  branch_id: z.string().uuid().optional(),
  cost_center_id: z.string().uuid().optional(),
  order_date: z.string().optional(),
  expected_delivery_date: z.string().optional(),
  notes: z.string().max(2000).optional(),
  terms: z.string().max(2000).optional(),
  created_by: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
  lines: z.array(z.object({
    item_id: z.string().uuid().optional(),
    item_code: z.string().max(50).optional(),
    item_name: z.string().max(200).optional(),
    description: z.string().max(1000).optional(),
    qty: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
    unit: z.string().default('piece'),
    unit_price: z.number().min(0),
    unit_cost: z.number().min(0).optional(),
    discount_percent: z.number().min(0).max(100).optional(),
    tax_rate: z.number().min(0).optional(),
    warehouse_id: z.string().uuid().optional(),
  })).min(1, 'يجب إضافة بند واحد على الأقل'),
})

export const CreateInvoiceSchema = z.object({
  order_id: z.string().uuid().optional(),
  customer_id: z.string().uuid('العميل مطلوب'),
  customer_name: z.string().max(200).optional(),
  branch_id: z.string().uuid().optional(),
  cost_center_id: z.string().uuid().optional(),
  invoice_type: z.string().default('standard'),
  invoice_date: z.string().optional(),
  due_date: z.string().optional(),
  notes: z.string().max(2000).optional(),
  terms: z.string().max(2000).optional(),
  created_by: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
  lines: z.array(z.object({
    item_id: z.string().uuid().optional(),
    item_code: z.string().max(50).optional(),
    item_name: z.string().max(200).optional(),
    description: z.string().max(1000).optional(),
    qty: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
    unit: z.string().default('piece'),
    unit_price: z.number().min(0),
    unit_cost: z.number().min(0).optional(),
    discount_percent: z.number().min(0).max(100).optional(),
    tax_rate: z.number().min(0).optional(),
    warehouse_id: z.string().uuid().optional(),
    account_revenue_id: z.string().uuid().optional(),
    account_cogs_id: z.string().uuid().optional(),
  })).min(1, 'يجب إضافة بند واحد على الأقل'),
})

export const CreatePaymentSchema = z.object({
  customer_id: z.string().uuid('العميل مطلوب'),
  customer_name: z.string().max(200).optional(),
  payment_type: z.enum(['cash', 'bank_transfer', 'cheque', 'credit_card', 'wallet', 'pos', 'online']),
  payment_date: z.string().optional(),
  amount: z.number().positive('المبلغ يجب أن يكون أكبر من صفر'),
  currency: z.string().default('SAR'),
  reference: z.string().max(100).optional(),
  cheque_no: z.string().max(50).optional(),
  cheque_date: z.string().optional(),
  bank_account: z.string().max(100).optional(),
  notes: z.string().max(1000).optional(),
  created_by: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
  allocations: z.array(z.object({
    invoice_id: z.string().uuid().optional(),
    credit_note_id: z.string().uuid().optional(),
    amount: z.number().positive(),
  })).optional(),
})

export const CreateReturnSchema = z.object({
  invoice_id: z.string().uuid().optional(),
  customer_id: z.string().uuid('العميل مطلوب'),
  customer_name: z.string().max(200).optional(),
  branch_id: z.string().uuid().optional(),
  warehouse_id: z.string().uuid().optional(),
  return_type: z.string().default('partial'),
  reason: z.string().max(2000).optional(),
  reason_ar: z.string().max(2000).optional(),
  created_by: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
  lines: z.array(z.object({
    invoice_line_id: z.string().uuid().optional(),
    item_id: z.string().uuid('الصنف مطلوب'),
    qty: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
    unit_price: z.number().min(0),
    unit_cost: z.number().min(0).optional(),
    condition: z.enum(['new', 'good', 'damaged', 'defective']).optional(),
    reason: z.string().max(500).optional(),
  })).min(1, 'يجب إضافة بند واحد على الأقل'),
})

export const CreateShipmentSchema = z.object({
  order_id: z.string().uuid().optional(),
  invoice_id: z.string().uuid().optional(),
  warehouse_id: z.string().uuid('المستودع مطلوب'),
  customer_id: z.string().uuid('العميل مطلوب'),
  shipping_address: z.string().max(500).optional(),
  carrier: z.string().max(100).optional(),
  tracking_no: z.string().max(100).optional(),
  notes: z.string().max(1000).optional(),
  created_by: z.string().uuid().optional(),
  lines: z.array(z.object({
    order_line_id: z.string().uuid().optional(),
    item_id: z.string().uuid('الصنف مطلوب'),
    qty: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
    batch_id: z.string().uuid().optional(),
  })).min(1, 'يجب إضافة بند واحد على الأقل'),
})
