import type { SupabaseClient } from '@supabase/supabase-js'
import { JournalRepository } from '../repositories/journal.repository'
import { AccountRepository } from '../repositories/account.repository'
import { PeriodRepository } from '../repositories/period.repository'
import { CreateJournalEntrySchema, JournalQuerySchema, PostJournalActionSchema } from '../validators/journal.schema'
import type { JournalEntryEntity, CreateJournalEntryInput, PostJournalResult } from '../entities/journal.entity'
import type { ServiceResult, JournalStatus } from '../types'

export class JournalService {
  private readonly repo: JournalRepository
  private readonly accountRepo: AccountRepository
  private readonly periodRepo: PeriodRepository

  constructor(
    private readonly db: SupabaseClient,
    private readonly companyId: string,
  ) {
    this.repo = new JournalRepository(db, companyId)
    this.accountRepo = new AccountRepository(db, companyId)
    this.periodRepo = new PeriodRepository(db, companyId)
  }

  async create(input: CreateJournalEntryInput): Promise<ServiceResult<PostJournalResult>> {
    const parsed = CreateJournalEntrySchema.safeParse(input)
    if (!parsed.success) {
      return { ok: false, error: parsed.error.errors.map(e => e.message).join('; '), code: 'VALIDATION_ERROR' }
    }

    const entryDate = parsed.data.date || new Date().toISOString().slice(0, 10)

    const period = await this.periodRepo.findOpenPeriodByDate(entryDate)
    if (!period) {
      return { ok: false, error: 'لا توجد فترة مالية مفتوحة لهذا التاريخ', code: 'NO_OPEN_PERIOD' }
    }

    const resolvedLines: Array<{
      account_id: string
      debit: number
      credit: number
      description: string | null
      line_number: number
      cost_center_id: string | null
      branch_id: string | null
    }> = []

    for (let i = 0; i < parsed.data.lines.length; i++) {
      const line = parsed.data.lines[i]
      let accountId = line.account_id

      if (!accountId && line.account_code) {
        const account = await this.accountRepo.findByCode(line.account_code)
        if (!account) {
          return { ok: false, error: `الحساب غير موجود: ${line.account_code}`, code: 'ACCOUNT_NOT_FOUND' }
        }
        if (!account.is_postable) {
          return { ok: false, error: `الحساب ${account.name} غير قابل للترحيل`, code: 'NON_POSTABLE_ACCOUNT' }
        }
        accountId = account.id
      }

      if (!accountId) {
        return { ok: false, error: `السطر ${i + 1}: لم يتم تحديد الحساب`, code: 'MISSING_ACCOUNT' }
      }

      resolvedLines.push({
        account_id: accountId,
        debit: line.debit,
        credit: line.credit,
        description: line.description || null,
        line_number: i + 1,
        cost_center_id: (line.cost_center_id as string | undefined) ?? null,
        branch_id: (line.branch_id as string | undefined) ?? null,
      })
    }

    const totalDebit = resolvedLines.reduce((s, l) => s + l.debit, 0)
    const totalCredit = resolvedLines.reduce((s, l) => s + l.credit, 0)

    try {
      const entryNumber = await this.repo.getNextEntryNumber()
      const isAutoGenerated = parsed.data.source === 'auto_generated'

      const { data: entry, error } = await this.db
        .from('journal_entries')
        .insert({
          company_id: this.companyId,
          entry_number: entryNumber,
          date: entryDate,
          description: parsed.data.description,
          description_ar: parsed.data.description_ar || parsed.data.description,
          reference: parsed.data.reference || null,
          source: parsed.data.source || 'manual',
          source_id: parsed.data.source_id || null,
          source_document: parsed.data.source_document || null,
          status: isAutoGenerated ? 'posted' : 'draft',
          approval_status: 'approved',
          is_posted: isAutoGenerated,
          is_balanced: true,
          auto_generated: isAutoGenerated,
          total_debit: totalDebit,
          total_credit: totalCredit,
          fiscal_year_id: period.fiscal_year_id,
          period_id: period.id,
          branch_id: parsed.data.branch_id || null,
          cost_center_id: parsed.data.cost_center_id || null,
          created_by_id: parsed.data.created_by_id || null,
          currency: parsed.data.currency || 'SAR',
          exchange_rate: parsed.data.exchange_rate || 1,
          tags: parsed.data.tags || null,
          posted_at: isAutoGenerated ? new Date().toISOString() : null,
        })
        .select('id, entry_number')
        .single()

      if (error || !entry) {
        return { ok: false, error: `فشل إنشاء القيد: ${error?.message}`, code: 'CREATE_FAILED' }
      }

      await this.repo.insertLines(
        resolvedLines.map(l => ({ ...l, journal_entry_id: entry.id }))
      )

      if (isAutoGenerated) {
        await this.updateAccountBalances(resolvedLines)
      }

      return {
        ok: true,
        data: { journal_id: entry.id, entry_number: entry.entry_number },
      }
    } catch (e: any) {
      return { ok: false, error: e.message, code: 'CREATE_FAILED' }
    }
  }

  async post(journalId: string, approvedById?: string): Promise<ServiceResult<PostJournalResult>> {
    const entry = await this.repo.findByIdWithLines(journalId)
    if (!entry) return { ok: false, error: 'القيد غير موجود', code: 'NOT_FOUND' }

    if (entry.status === 'posted') return { ok: false, error: 'القيد مرحّل بالفعل', code: 'ALREADY_POSTED' }
    if (entry.status === 'void') return { ok: false, error: 'لا يمكن ترحيل قيد ملغي', code: 'VOID_ENTRY' }
    if (entry.status === 'reversed') return { ok: false, error: 'لا يمكن ترحيل قيد معكوس', code: 'REVERSED_ENTRY' }

    const period = await this.periodRepo.findOpenPeriodByDate(entry.date)
    if (!period) {
      return { ok: false, error: 'لا توجد فترة مالية مفتوحة لهذا التاريخ', code: 'NO_OPEN_PERIOD' }
    }

    try {
      await this.repo.updateStatus(journalId, 'posted', {
        is_posted: true,
        approved_by_id: approvedById || null,
        posted_at: new Date().toISOString(),
        period_id: period.id,
      })

      if (entry.lines) {
        await this.updateAccountBalances(
          entry.lines.map(l => ({
            account_id: l.account_id,
            debit: l.debit,
            credit: l.credit,
            description: l.description,
            line_number: l.line_number,
            cost_center_id: l.cost_center_id || null,
            branch_id: l.branch_id || null,
          }))
        )
      }

      return {
        ok: true,
        data: { journal_id: journalId, entry_number: entry.entry_number },
      }
    } catch (e: any) {
      return { ok: false, error: e.message, code: 'POST_FAILED' }
    }
  }

  async reverse(journalId: string, reason?: string): Promise<ServiceResult<PostJournalResult>> {
    const entry = await this.repo.findByIdWithLines(journalId)
    if (!entry) return { ok: false, error: 'القيد غير موجود', code: 'NOT_FOUND' }
    if (entry.status !== 'posted') return { ok: false, error: 'يمكن عكس القيود المرحّلة فقط', code: 'NOT_POSTED' }
    if (entry.reversal_entry_id) return { ok: false, error: 'هذا القيد تم عكسه مسبقاً', code: 'ALREADY_REVERSED' }

    if (!entry.lines) return { ok: false, error: 'القيد لا يحتوي على بنود', code: 'NO_LINES' }

    const today = new Date().toISOString().slice(0, 10)
    const reversedLines = entry.lines.map(l => ({
      account_code: '',
      account_id: l.account_id,
      debit: l.credit,
      credit: l.debit,
      description: l.description ? `عكس: ${l.description}` : 'قيد عكسي',
      cost_center_id: l.cost_center_id ?? undefined,
      branch_id: l.branch_id ?? undefined,
    }))

    const createResult = await this.create({
      company_id: this.companyId,
      description: `عكس قيد: ${entry.description}${reason ? ` - ${reason}` : ''}`,
      description_ar: `عكس قيد: ${entry.description_ar || entry.description}`,
      reference: entry.reference || undefined,
      source: 'reversal',
      source_id: journalId,
      source_document: `Reversal of ${entry.entry_number}`,
      date: today,
      lines: reversedLines,
    })

    if (!createResult.ok) return createResult

    await this.repo.updateStatus(journalId, 'reversed', {
      reversal_entry_id: createResult.data.journal_id,
      reversal_reason: reason || null,
    })

    await this.repo.updateStatus(createResult.data.journal_id, 'posted', {
      reversal_of: journalId,
    })

    return createResult
  }

  async voidEntry(journalId: string): Promise<ServiceResult<{ id: string }>> {
    const entry = await this.repo.findByIdWithLines(journalId)
    if (!entry) return { ok: false, error: 'القيد غير موجود', code: 'NOT_FOUND' }
    if (!['draft', 'pending'].includes(entry.status)) {
      return { ok: false, error: 'يمكن إلغاء القيود في حالة المسودة أو المعلقة فقط', code: 'INVALID_STATUS' }
    }

    try {
      await this.repo.updateStatus(journalId, 'void')
      return { ok: true, data: { id: journalId } }
    } catch (e: any) {
      return { ok: false, error: e.message, code: 'VOID_FAILED' }
    }
  }

  async getById(id: string): Promise<ServiceResult<JournalEntryEntity>> {
    const entry = await this.repo.findByIdWithLines(id)
    if (!entry) return { ok: false, error: 'القيد غير موجود', code: 'NOT_FOUND' }
    return { ok: true, data: entry }
  }

  async list(filters: {
    status?: string
    source?: string
    fromDate?: string
    toDate?: string
    periodId?: string
    search?: string
    page?: number
    limit?: number
  }): Promise<ServiceResult<{ data: JournalEntryEntity[]; count: number }>> {
    const parsed = JournalQuerySchema.safeParse({
      ...filters,
      page: filters.page || 1,
      limit: filters.limit || 50,
    })
    if (!parsed.success) {
      return { ok: false, error: parsed.error.errors.map(e => e.message).join('; '), code: 'VALIDATION_ERROR' }
    }

    try {
      const result = await this.repo.findPaged({
        ...parsed.data,
        fromDate: parsed.data.from_date,
        toDate: parsed.data.to_date,
        periodId: parsed.data.period_id,
        fiscalYearId: parsed.data.fiscal_year_id,
        branchId: parsed.data.branch_id,
        costCenterId: parsed.data.cost_center_id,
        sortBy: parsed.data.sort_by,
        sortOrder: parsed.data.sort_order,
      })
      return { ok: true, data: result }
    } catch (e: any) {
      return { ok: false, error: e.message, code: 'FETCH_FAILED' }
    }
  }

  async countByStatus(status: string): Promise<number> {
    return this.repo.countByStatus(status)
  }

  private async updateAccountBalances(
    lines: Array<{ account_id: string; debit: number; credit: number }>,
  ): Promise<void> {
    for (const line of lines) {
      const { data: totals } = await this.db
        .from('journal_entry_lines')
        .select('debit, credit, journal_entries!inner(status, company_id)')
        .eq('account_id', line.account_id)
        .eq('journal_entries.company_id', this.companyId)
        .eq('journal_entries.status', 'posted')

      const totalDebit = (totals || []).reduce((s: number, r: any) => s + Number(r.debit || 0), 0)
      const totalCredit = (totals || []).reduce((s: number, r: any) => s + Number(r.credit || 0), 0)

      const { data: acct } = await this.db
        .from('accounts')
        .select('normal_balance')
        .eq('id', line.account_id)
        .maybeSingle()

      const balance = acct?.normal_balance === 'debit'
        ? totalDebit - totalCredit
        : totalCredit - totalDebit

      await this.db
        .from('accounts')
        .update({ current_balance: balance })
        .eq('id', line.account_id)
    }
  }
}
