import { z } from 'zod'

export const CreateItemSchema = z.object({
  code: z.string().min(1, 'رمز الصنف مطلوب').max(50),
  name: z.string().min(1, 'اسم الصنف مطلوب').max(200),
  name_ar: z.string().max(200).optional(),
  description: z.string().max(2000).optional(),
  category: z.string().max(100).optional(),
  subcategory: z.string().max(100).optional(),
  type: z.enum(['product', 'service', 'raw_material', 'wip', 'finished_good', 'consumable', 'asset', 'packaging']).default('product'),
  unit: z.string().default('piece'),
  cost_method: z.enum(['fifo', 'weighted_average', 'standard']).default('weighted_average'),
  standard_cost: z.number().min(0).default(0),
  is_tracked: z.boolean().default(true),
  is_serialized: z.boolean().default(false),
  is_batch_tracked: z.boolean().default(false),
  has_expiry: z.boolean().default(false),
  shelf_life_days: z.number().int().positive().optional(),
  barcode: z.string().max(100).optional(),
  sku: z.string().max(100).optional(),
  tax_rate_id: z.string().uuid().optional(),
  account_revenue_id: z.string().uuid().optional(),
  account_cogs_id: z.string().uuid().optional(),
  account_inventory_id: z.string().uuid().optional(),
  default_warehouse_id: z.string().uuid().optional(),
  min_stock: z.number().min(0).default(0),
  max_stock: z.number().min(0).optional(),
  reorder_point: z.number().min(0).default(0),
  reorder_qty: z.number().min(0).default(0),
  lead_time_days: z.number().int().min(0).default(0),
  metadata: z.record(z.unknown()).optional(),
})

export const CreateMovementSchema = z.object({
  item_id: z.string().uuid('الصنف مطلوب'),
  variant_id: z.string().uuid().optional(),
  batch_id: z.string().uuid().optional(),
  warehouse_id: z.string().uuid('المستودع مطلوب'),
  location_id: z.string().uuid().optional(),
  to_warehouse_id: z.string().uuid().optional(),
  to_location_id: z.string().uuid().optional(),
  movement_type: z.enum([
    'receipt', 'issue', 'transfer_out', 'transfer_in', 'return',
    'adjustment_up', 'adjustment_down', 'reservation', 'unreservation',
    'manufacturing_issue', 'manufacturing_completion', 'scrap', 'write_off',
    'recount_up', 'recount_down', 'initial_balance',
  ]),
  direction: z.enum(['in', 'out', 'internal']),
  qty: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
  unit_cost: z.number().min(0).default(0),
  total_cost: z.number().min(0).default(0),
  unit_price: z.number().min(0).optional(),
  reference_type: z.string().max(50).optional(),
  reference_id: z.string().uuid().optional(),
  reference_line_id: z.string().uuid().optional(),
  source: z.string().min(1, 'المصدر مطلوب'),
  source_id: z.string().optional(),
  description: z.string().max(500).optional(),
  created_by: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
})

export const CreateReservationSchema = z.object({
  item_id: z.string().uuid('الصنف مطلوب'),
  variant_id: z.string().uuid().optional(),
  batch_id: z.string().uuid().optional(),
  warehouse_id: z.string().uuid('المستودع مطلوب'),
  location_id: z.string().uuid().optional(),
  order_id: z.string().uuid().optional(),
  order_type: z.string().max(50).optional(),
  order_line_id: z.string().uuid().optional(),
  qty: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
  type: z.enum(['soft', 'hard', 'backorder']).default('soft'),
  expires_at: z.string().optional(),
  created_by: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
})
